### ISSUE TITLE
Zone File Download Broken due to Content-Dispostion Header Malformation

### ISSUE THREAD

**Issue by chadmichael** [icann/czds-api-client-python#12]
On 9/25, I started seeing failures of the downloads with a `KeyError` coming out of the download code.  The function `download_one_zone` parses the content-disposition header to get the filename.  Inspecting the actual header in the response, I see this:

`Content-Disposition: attachment; filename*=UTF-8''scot.txt.gz`

And here's what the code does with it ... 

```
>>> field1, field2 = cgi.parse_header("Content-Disposition: attachment; filename*=UTF-8''scot.txt.gz")
>>> field1
'Content-Disposition: attachment'
>>> field2
{'filename*': "UTF-8''scot.txt.gz"}
>>> field2['filename']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'filename'
```

Looking at the code, it doesn't appear that this would have ever worked.  It's supposed to move on to creating a name via other means, but this exception prevents that.  Either the web server started serving different headers, and the header does appear to be broken, or the cgi module started being stricter when parsing ... 
 

https://github.com/icann/czds-api-client-python/blob/7b49a2fde2619c8c7de6915017088440a1d33f09/download.py#L112

**Comment by chadmichael** [comment]
aha ... I see you added a fix ....

**Comment by chandrawisnu** [comment]
ProTip! Type g p on any issue or pull request to go back to the pull request listing page.
© 2021 GitHub, Inc.
